#!/bin/sh

exec cmake \
  -Bbuild \
  -Hllvm \
  -DBUILD_SHARED_LIBS=ON \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_INSTALL_PREFIX="$HOME/.local" \
  -DLLVM_CCACHE_BUILD=ON \
  -DLLVM_ENABLE_EH=ON \
  -DLLVM_ENABLE_EXPENSIVE_CHECKS=ON \
  -DLLVM_ENABLE_FFI=ON \
  -DLLVM_ENABLE_RTTI=ON \
  -DLLVM_ENABLE_Z3_SOLVER=ON \
  -DLLVM_ENABLE_PROJECTS=all \
  -DLLVM_OPTIMIZED_TABLEGEN=ON \
  -DLLVM_PARALLEL_LINK_JOBS=1 \
  -DLLVM_USE_LINKER=mold \
  -G Ninja
